version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres_gutenberg
    restart: always
    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_projet
      POSTGRES_DB: bibliotheque_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - gutentax_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_gui
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@projet.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - gutentax_network

networks:
  gutentax_network:
    driver: bridge

volumes:
  pgdata: